# Generated by Django 5.0.1 on 2024-01-16 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_event_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
