# Generated by Django 5.0.1 on 2024-01-18 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='events',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.event'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
